MaltAuction/MaltAuction/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MaltAuction.views.home', name = 'home'),
    # url(r'^blog/', include('blog.urls')),
    
    url(r'^$', include('home.urls', namespace = 'home')),
    url(r'^about/$', TemplateView.as_view(template_name = 'about.html'), name = 'about'),
    url(r'^bottles/', include('bottles.urls', namespace = "bottles")),
    url(r'^auction/', include('auction.urls', namespace = "auction")),
    url(r'^users/', include('users.urls', namespace = "users")),
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

MaltAuction/bottles/urls.py
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

from bottles import views

urlpatterns = patterns('',
    # Lists
    url(r'^bottle/list/$', views.bottles_list, name = "bottles_list"),
    url(r'^bottle/list/(?P<letter>\w)/$', views.bottles_list_alpha, name = "bottles_list_alpha"),
    url(r'^bottle/list/brand/(?P<brand>\w+)/$', views.bottles_list_brand, name = "bottles_list_brand"),
    url(r'^bottle/list/distillery/(?P<distillery>\w+)/$', views.bottles_list_distillery, name = "bottles_list_distillery"),
    url(r'^distillery/list/$', views.distilleries_list, name = "distilleries_list"),
    url(r'^distillery/list/(?P<letter>\w)/$', views.distilleries_list_alpha, name = "distilleries_list_alpha"),
    url(r'^region/(?P<letter>\w)/$', views.region, name = "region"),
    url(r'^brand/list/$', views.brands_list, name = "brands_list"),
    url(r'^brand/list/(?P<letter>\w)/$', views.brands_list_alpha, name = "brands_list_alpha"),
    
    # Add
    url(r'^bottle/new/$', views.bottle_new, name = 'bottle_new'),
    url(r'^distillery/new/$', views.distillery_new, name = 'distillery_new'),
    url(r'^brand/new/$', views.brand_new, name = 'brand_new'),
    
    # Search
    url(r'^bottle/search/', views.bottle_search, name = "bottle_search"),
    url(r'^distillery/search/', views.distillery_search, name = "distillery_search"),
    url(r'^brand/search/', views.brand_search, name = "brand_search"),
    
    # Details
    url(r'^bottle/(?P<bottle_id>\d+)/$', views.bottle, name = "bottle"),    
    url(r'^distillery/(?P<distillery_name>\w+)/$', views.distillery, name = "distillery"),
    
    # Delete
    url(r'^bottle/delete/(?P<bottle_id>\d+)/$', views.bottle_delete, name = "bottle_delete"),
    url(r'^distillery/delete/(?P<distillery_name>\w+)/$', views.distillery_delete, name = "distillery_delete"),
    
    # Edit
    url(r'^bottle/edit/(?P<bottle_id>\d+)/$', views.bottle_edit, name = 'bottle_edit'),
    url(r'^distillery/edit/(?P<distillery_name>\w+)/$', views.distillery_edit, name = 'distillery_edit'),
     
) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

MaltAuction/home/urls.py
from django.conf.urls import patterns, url
from home import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',
    url(r'^$', views.home, name = 'home'),
) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

MaltAuction/home/models.py
from django.db import models

# Create your models here.

MaltAuction/home/views.py
from django.shortcuts import render
from bottles.models import Bottle, Distillery, Brand

# Create your views here.
def home(request):
    # Distilleries by regions
    REGION_CHOICES = ('C', 'H', 'D', 'I', 'L', 'S', 'R', 'J', 'U', 'W')
    by_region = []
    for r in REGION_CHOICES:
        another = Distillery.objects.filter(region = r).order_by('name')
        by_region.append(another)
        
    # Last bottles added - Pasandoselo a la plantilla
    bottles = Bottle.objects.all()[:5]
        
    context = {'by_region':by_region, 'bottles':bottles}
    return render(request, 'home/home.html', context)

MaltAuction/home/templates/home/home.html
{% extends "base.html" %}

{% block Contents %}
	<h2>MALT WHISKY REGIONS AROUND THE WORLD</h2>
	{% for dists in by_region %}
		<div class='fivecolumns'>
		{% for data in dists %}
			{% if forloop.first %}
				<h3><a href="{% url 'bottles:region' data.region %}">{{data.get_region_display}}</a></h3>
			{% endif %}
	    	<div class='cell'>
	    		<div class='celltext'>
	    			<div class='{{data.status}}'>
	    				<a href="{% url 'bottles:distillery' data.name %}">
 							<img src='{{MEDIA_URL}}{{data.picture}}' alt=""/>{{ data.name }} ({{ data.yearFounded }})
 						</a>
	            		<p>{{data.description|truncatewords:"10"}}</p>
					</div>
				</div>
			</div>
			{% if forloop.counter|divisibleby:"5" %}
			</div>
			<div class='fivecolumns'>
			{% endif %}
		{% endfor %}
		</div>
	{% endfor %}
{% endblock %}

{% block Aside %}
	<h3>Last added bottles</h3>
	{% for bottle in bottles %}
		<img style="width:50px;" align="right" src='{{MEDIA_URL}}{{bottle.picture}}'>
		<h5>{{ bottle.name }}</h5>	
		<p>		
		From {{ bottle.brand.distillery.name }} distillery<br>
		{% if bottle.age %}
			{{ bottle.age }} year(s) old<br>
		{% endif %}
		{{ bottle.strength }} abv<br>	
		</p>
	{% endfor %}
{% endblock %}