MaltAuction/MaltAuction/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MaltAuction.views.home', name = 'home'),
    # url(r'^blog/', include('blog.urls')),
    
    url(r'^$', include('home.urls', namespace = 'home')),
    url(r'^about/$', TemplateView.as_view(template_name = 'about.html'), name = 'about'),
    url(r'^bottles/', include('bottles.urls', namespace = "bottles")),
    url(r'^auction/', include('auction.urls', namespace = "auction")),
    url(r'^users/', include('users.urls', namespace = "users")),
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

MaltAuction/bottles/urls.py
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

from bottles import views

urlpatterns = patterns('',
    # Lists
    url(r'^bottle/list/$', views.bottles_list, name = "bottles_list"),
    url(r'^bottle/list/(?P<letter>\w)/$', views.bottles_list_alpha, name = "bottles_list_alpha"),
    url(r'^bottle/list/brand/(?P<brand>\w+)/$', views.bottles_list_brand, name = "bottles_list_brand"),
    url(r'^bottle/list/distillery/(?P<distillery>\w+)/$', views.bottles_list_distillery, name = "bottles_list_distillery"),
    url(r'^distillery/list/$', views.distilleries_list, name = "distilleries_list"),
    url(r'^distillery/list/(?P<letter>\w)/$', views.distilleries_list_alpha, name = "distilleries_list_alpha"),
    url(r'^region/(?P<letter>\w)/$', views.region, name = "region"),
    url(r'^brand/list/$', views.brands_list, name = "brands_list"),
    url(r'^brand/list/(?P<letter>\w)/$', views.brands_list_alpha, name = "brands_list_alpha"),
    
    # Add
    url(r'^bottle/new/$', views.bottle_new, name = 'bottle_new'),
    url(r'^distillery/new/$', views.distillery_new, name = 'distillery_new'),
    url(r'^brand/new/$', views.brand_new, name = 'brand_new'),
    
    # Search
    url(r'^bottle/search/', views.bottle_search, name = "bottle_search"),
    url(r'^distillery/search/', views.distillery_search, name = "distillery_search"),
    url(r'^brand/search/', views.brand_search, name = "brand_search"),
    
    # Details
    url(r'^bottle/(?P<bottle_id>\d+)/$', views.bottle, name = "bottle"),    
    url(r'^distillery/(?P<distillery_name>\w+)/$', views.distillery, name = "distillery"),
    
    # Delete
    url(r'^bottle/delete/(?P<bottle_id>\d+)/$', views.bottle_delete, name = "bottle_delete"),
    url(r'^distillery/delete/(?P<distillery_name>\w+)/$', views.distillery_delete, name = "distillery_delete"),
    
    # Edit
    url(r'^bottle/edit/(?P<bottle_id>\d+)/$', views.bottle_edit, name = 'bottle_edit'),
    url(r'^distillery/edit/(?P<distillery_name>\w+)/$', views.distillery_edit, name = 'distillery_edit'),
     
) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

MaltAuction/home/urls.py
from django.conf.urls import patterns, url
from home import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',
    url(r'^$', views.home, name = 'home'),
) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

MaltAuction/users/urls.py
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from users.views import RegisterUser, LoginUser, LogoutUser, UpdateProfile

urlpatterns = patterns('',
    url(r'^register/$', RegisterUser.as_view(), name = "register"),
    url(r'^update/(?P<pk>\d+)/$', UpdateProfile.as_view(), name = "update"),
    url(r'^login/$', LoginUser.as_view(), name = 'login'),
    url(r'^logout/$', LogoutUser.as_view(), name = 'logout'),
    url(r'^change_passwd/', 'django.contrib.auth.views.password_change', 
        {'template_name':'users/passwd_change_form.html', 'post_change_redirect' : 'home:home'}, name = "change_passwd"), 
) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

MaltAuction/MaltAuction/templates/about.html
{% extends "base.html" %}

{% block Contents %}
	<h2>About Malt Auction</h2>
	<p>This a project for teaching Web Programming to undergraduate students</p>
{% endblock %}

MaltAuction/MaltAuction/templates/base.html
<!DOCTYPE html>

{% load static %}
{% load staticfiles %}


<html>
    <head>  
        <meta charset="utf-8">        
        <title>Base HTML page for Malt Aunction webpage</title>
           
        <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">       
    	
    	<!-- Le styles -->
    	<link href="http://getbootstrap.com/2.3.2/assets/css/bootstrap.css" rel="stylesheet">
    	<link href="http://getbootstrap.com/2.3.2/assets/css/bootstrap-responsive.css" rel="stylesheet">
    	
    	<link href="http://getbootstrap.com/examples/carousel/carousel.css" rel="stylesheet">
    	
    	<!-- Local CSS -->
    	<link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}">
    </head>

    <body>    
    	{% block NavigationTop %}
    	<div class="container">
	    	<nav class="navbar navbar-inverse">
	        	<div class="navbar-header">
	          		<a class="navbar-brand" href="{% url 'about' %}">Malt Auction</a>
	        	</div>
	        	<div>
	          		<ul class="nav navbar-nav">
	            		<li class="active"><a href="{% url 'home:home' %}">Home</a></li>	            
						<li class="dropdown">
				          <a data-target="#" href="{% url 'bottles:distilleries_list' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
				          		Distilleries <span class="caret"></span></a>
				          <ul class="dropdown-menu" role="menu">
				            <li><a href="{% url 'bottles:distilleries_list' %}">List</a></li>
				            <li class="divider"></li>
				            <li><a href="{% url 'bottles:distillery_new' %}">New distillery</a></li>
				          </ul>
				        </li>
				        <li class="dropdown">
				          <a data-target="#" href="{% url 'bottles:brands_list' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
				          		Brands <span class="caret"></span></a>
				          <ul class="dropdown-menu" role="menu">
				            <li><a href="{% url 'bottles:brands_list' %}">List</a></li>
				            <li class="divider"></li>
				            <li><a href="{% url 'bottles:brand_new' %}">New brand</a></li>
				          </ul>
				        </li>
	            		<li class="dropdown">
				          <a data-target="#" href="{% url 'bottles:bottles_list' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
				          		Bottles <span class="caret"></span></a>
				          <ul class="dropdown-menu" role="menu">
				            <li><a href="{% url 'bottles:bottles_list' %}">List</a></li>
				            <li><a href="#">In auction</a></li>
				            <li><a href="#">Auctioned</a></li>
				            <li class="divider"></li>
				            <li><a href="{% url 'bottles:bottle_new' %}">New bottle</a></li>
				          </ul>
				        </li>
	          		</ul>
	          		<ul class="nav navbar-nav navbar-right">	            		
	            		{% if user.is_authenticated %}
	            			<li><a href="{% url 'users:update' user.pk %}"><span class="glyphicon glyphicon-user"></span> Update profile</a></li>
	            			<li><a href="{% url 'users:change_passwd' %}"><span class="glyphicon glyphicon-edit"></span> Change password</a></li>
	            			<li><a href="{% url 'users:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>	            			
	            		{% else %}
	            			<li><a href="{% url 'users:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
	            			<li><a href="{% url 'users:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>	            			
	            		{% endif %}
	          		</ul>
	        	</div>	      
	    	</nav>
	    </div>
	    {% endblock %}
	    
	    <div class="container">
	    	<!-- Carousel begins -->
			<div id="headings-carousel" class="carousel slide" data-ride="carousel">
		  		<!-- Indicators -->
		  		<ol class="carousel-indicators">
		    		<li data-target="#headings-carousel" data-slide-to="0" class="active"></li>
		    		<li data-target="#headings-carousel" data-slide-to="1"></li>
		    		<li data-target="#headings-carousel" data-slide-to="2"></li>
		  		</ol>
		 
			  	<!-- Wrapper for slides -->
			  	<div class="carousel-inner">
			    	<div class="item active">
			      		<img src="{% static "img/slide1.jpg" %}" alt="First slide">
			      		<div class="carousel-caption">
	             			<h1>Best Single Malt auction in the world</h1>
	              			<p>"Listen, if we can't break the ice, how 'bout we drown it?"</p>
	             			<p><a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Sign up today</a></p>
	            		</div>
			    	</div>
			    	<div class="item">
			    		<img src="{% static "img/slide2.jpg" %}" alt="Second slide">
			    		<div class="carousel-caption">
	              			<h1>Join the fun.</h1>
	             			 <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
	            		</div>
			   	 	</div>
			    	<div class="item">
			      		<img src="{% static "img/slide3.jpg" %}" alt="Third slide">
			      		<div class="carousel-caption">
			        		<h3>Start browsing</h3>
			      		</div>
			    	</div>
			  	</div>
	 
				<!-- Controls -->
			  	<a class="left carousel-control" href="#headings-carousel" role="button" data-slide="prev">
			    	<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			    	<span class="sr-only">Previous</span>
			  	</a>			  	
			  	<a class="right carousel-control" href="#headings-carousel" role="button" data-slide="next" style="z-index: 1000;">
			    	<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				    <span class="sr-only">Next</span>
				</a>
			</div> 
			<!-- Carousel ends -->
		</div>

        <div class="container">
        	<!-- 
            <div class="jumbotron">
			 	<header>
	            	<h1>{% block Header %}Malt Auction Webpage{% endblock %}</h1>
	        	</header>
	        </div>
	        -->	         	     	        
	  		<div class="row">
	        	<div class="col-md-2">
	            	{% block NavigationLeft %}
	            	<ul class="nav nav-tabs nav-stacked">
					    <li><a href="{% url 'home:home' %}">Home</a></li>					   
	            	    <li class="dropdown">
				          <a data-target="#" href="{% url 'bottles:distilleries_list' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
				          		Distilleries <span class="caret"></span></a>
				          <ul class="dropdown-menu" role="menu">
				            <li><a href="{% url 'bottles:distilleries_list' %}">List</a></li>
				            <li class="divider"></li>
				            <li><a href="{% url 'bottles:distillery_new' %}">New distillery</a></li>
				          </ul>
				        </li>
	             	    <li class="dropdown">
				          <a data-target="#" href="{% url 'bottles:brands_list' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
				          		Brands <span class="caret"></span></a>
				          <ul class="dropdown-menu" role="menu">
				            <li><a href="{% url 'bottles:brands_list' %}">List</a></li>
				            <li class="divider"></li>
				            <li><a href="{% url 'bottles:brand_new' %}">New brand</a></li>
				          </ul>
				        </li>
	              	    <li class="dropdown">
				          <a data-target="#" href="{% url 'bottles:bottles_list' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
				          		Bottles <span class="caret"></span></a>
				          <ul class="dropdown-menu" role="menu">
				            <li><a href="{% url 'bottles:bottles_list' %}">List</a></li>
				            <li><a href="#">In auction</a></li>
				            <li><a href="#">Auctioned</a></li>
				            <li class="divider"></li>
				            <li><a href="{% url 'bottles:bottle_new' %}">New bottle</a></li>
				          </ul>
				        </li>              	
	              	</ul>
	                {% endblock %}
	            </div>
	                  
	            <div class="col-md-8">
		            {% block Contents %}
		                <h2>Welcome to Malt Auction web</h2> 				
		    		{% endblock %}
	    		</div>
	                       
	        	<div class="col-md-2">
		            <aside>
		            {% block Aside %}
		                <h3>
		                    <!-- Include some contextual information here -->
		                </h3>
		            {% endblock %}
		            </aside>      
	            </div>
	        </div>

	        <footer>
	        	{% block Footer %}
	           		&copy Nicolás García Pedrajas
	            {% endblock %}
	        </footer>
        </div>
        
	    <script src="http://getbootstrap.com/2.3.2/assets/js/jquery.js"></script>
	    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap.js"></script>  
	    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-transition.js"></script>
	    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-alert.js"></script>
	    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-modal.js"></script>
	    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-dropdown.js"></script>
	    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-scrollspy.js"></script>
	    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-tab.js"></script>
	    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-tooltip.js"></script>
	    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-popover.js"></script>
	    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-button.js"></script>
	    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-collapse.js"></script>
	    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-carousel.js"></script>
	    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-typeahead.js"></script>
	    <script>
	    	!function ($) {
	        	$(function(){
	          		// carousel demo
	          		$('#headings-carousel').carousel()
	        	})
	      	}(window.jQuery)
	    </script>
	    <script src="http://getbootstrap.com/2.3.2/assets/js/holder/holder.js"></script>
	    <script>$('.dropdown-toggle').dropdown()</script>
	</body>
</html> 