MaltAuction/MaltAuction/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MaltAuction.views.home', name = 'home'),
    # url(r'^blog/', include('blog.urls')),
    
    url(r'^$', include('home.urls', namespace = 'home')),
    url(r'^about/$', TemplateView.as_view(template_name = 'about.html'), name = 'about'),
    url(r'^bottles/', include('bottles.urls', namespace = "bottles")),
    url(r'^auction/', include('auction.urls', namespace = "auction")),
    url(r'^users/', include('users.urls', namespace = "users")),
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

MaltAuction/bottles/urls.py
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

from bottles import views

urlpatterns = patterns('',
    # Lists
    url(r'^bottle/list/$', views.bottles_list, name = "bottles_list"),
    url(r'^bottle/list/(?P<letter>\w)/$', views.bottles_list_alpha, name = "bottles_list_alpha"),
    url(r'^bottle/list/brand/(?P<brand>\w+)/$', views.bottles_list_brand, name = "bottles_list_brand"),
    url(r'^bottle/list/distillery/(?P<distillery>\w+)/$', views.bottles_list_distillery, name = "bottles_list_distillery"),
    url(r'^distillery/list/$', views.distilleries_list, name = "distilleries_list"),
    url(r'^distillery/list/(?P<letter>\w)/$', views.distilleries_list_alpha, name = "distilleries_list_alpha"),
    url(r'^region/(?P<letter>\w)/$', views.region, name = "region"),
    url(r'^brand/list/$', views.brands_list, name = "brands_list"),
    url(r'^brand/list/(?P<letter>\w)/$', views.brands_list_alpha, name = "brands_list_alpha"),
    
    # Add
    url(r'^bottle/new/$', views.bottle_new, name = 'bottle_new'),
    url(r'^distillery/new/$', views.distillery_new, name = 'distillery_new'),
    url(r'^brand/new/$', views.brand_new, name = 'brand_new'),
    
    # Search
    url(r'^bottle/search/', views.bottle_search, name = "bottle_search"),
    url(r'^distillery/search/', views.distillery_search, name = "distillery_search"),
    url(r'^brand/search/', views.brand_search, name = "brand_search"),
    
    # Details
    url(r'^bottle/(?P<bottle_id>\d+)/$', views.bottle, name = "bottle"),    
    url(r'^distillery/(?P<distillery_name>\w+)/$', views.distillery, name = "distillery"),
    
    # Delete
    url(r'^bottle/delete/(?P<bottle_id>\d+)/$', views.bottle_delete, name = "bottle_delete"),
    url(r'^distillery/delete/(?P<distillery_name>\w+)/$', views.distillery_delete, name = "distillery_delete"),
    
    # Edit
    url(r'^bottle/edit/(?P<bottle_id>\d+)/$', views.bottle_edit, name = 'bottle_edit'),
    url(r'^distillery/edit/(?P<distillery_name>\w+)/$', views.distillery_edit, name = 'distillery_edit'),
     
) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

MaltAuction/home/urls.py
from django.conf.urls import patterns, url
from home import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',
    url(r'^$', views.home, name = 'home'),
) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

MaltAuction/bottles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Distillery(models.Model):
    name = models.CharField(max_length = 100, primary_key = True)
    REGION_CHOICES = (
        ('C', 'Campbeltown'),
        ('H', 'Highlands'),
        ('D', 'Islands'),
        ('I', 'Islay'),
        ('L', 'Lowlands'),
        ('S', 'Speyside'),
        ('R', 'Ireland'),
        ('J', 'Japan'),
        ('U', 'USA'),
        ('W', 'Rest of the world'),
    )
    region = models.CharField(max_length = 1, choices = REGION_CHOICES)
    STATUS_CHOICES = (
        ('W', 'Working'),
        ('C', 'Closed'),
        ('D', 'Demolished'),
        ('M', 'Mothballed'),
        ('I', 'Dismantled'),
        ('S', 'Silent'),
    )
    status = models.CharField(max_length = 1, choices = STATUS_CHOICES, default = 'W')
    description = models.TextField(default = "")
    yearFounded = models.IntegerField('year founded')
    yearClosed = models.IntegerField(null = True, blank = True)
    webpage = models.URLField(null = True, blank = True)
    picture = models.ImageField(upload_to = 'distilleries', verbose_name = 'Picture', default = None)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name
    
    # Other methods can be added
    def print_details(self):
        return  "%s founded in %d and located in %s"  % (self.name, self.yearFounded, self.get_region_display())

class Brand(models.Model):
    name = models.CharField(max_length = 100, primary_key = True)
    description = models.TextField()
    distillery = models.ForeignKey(Distillery)

    def    __unicode__(self):
        return self.name

    def __str__(self):
        return self.name
    
    # For Python 3
    # def __str__(self):
    #   return self.name

class Bottle(models.Model):
    name = models.CharField(unique = True, max_length = 200)
    age = models.IntegerField(null = True, blank = True)
    vintage = models.IntegerField(null = True, blank = True)
    bottled = models.IntegerField(null = True, blank = True)
    distilleryBottling = models.BooleanField(default = True)
    independentBottler = models.CharField(max_length = 200, null = True, blank = True)
    strength = models.FloatField()
    brand = models.ForeignKey(Brand)
    comment = models.TextField(null = True, blank = True)
    cask = models.CharField(max_length = 100, null = True, blank = True)
    picture = models.ImageField(upload_to = 'bottles', verbose_name = 'Picture')
    bottles = models.IntegerField(null = True, blank = True)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

MaltAuction/bottles/forms.py
#encoding: utf-8
from django.forms.extras.widgets import SelectDateWidget
from django.forms import ModelForm
from django import forms
from bottles.models import Bottle, Distillery, Brand

class BottleForm(ModelForm):
    class Meta:
        model = Bottle
        
        # exclude = ['user', 'bottle', ]
        # fields = ['pub_date', 'headline', 'content', 'reporter']
        fields = '__all__'
        
    def __init__(self, *args, **kwargs):
        super(BottleForm, self).__init__(*args, **kwargs)
        self.fields['distilleryBottling'].label = "Distillery bottling"
        self.fields['independentBottler'].label = "Independent bottler"

class DistilleryForm(ModelForm):
    class Meta:
        model = Distillery
        
        fields = '__all__'
        
class BrandForm(ModelForm):
    class Meta:
        model = Brand
        
        fields = '__all__'

MaltAuction/bottles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from bottles.models import Bottle, Distillery, Brand
from django.contrib.auth.decorators import login_required
from bottles.forms import BottleForm, DistilleryForm, BrandForm
from django.core.urlresolvers import reverse_lazy
import string

# Create your views here.

# Lists
def bottles_list(request):
    """
    Returns list of all bottles ordered
    """
    bottles = Bottle.objects.all().order_by('name')
    letters = string.ascii_uppercase
    context = {'bottles': bottles, 'letters': letters}
    
    return render(request, "bottles/bottles.html", context)

def bottles_list_alpha(request, letter):
    """
    Returns list of all bottles starting with lettter ordered
    """
    bottles = Bottle.objects.filter(name__startswith = letter).order_by('name')
    letters = string.ascii_uppercase
    context = {'bottles': bottles, 'letters': letters}
    
    return render(request, "bottles/bottles.html", context)

def bottles_list_brand(request, brand):
    """
    Returns list of all bottles from a brand
    """
    bottles = Bottle.objects.filter(brand__name = brand).order_by('name')
    title = "Brand: " + brand
    context = {'bottles': bottles, 'title': title}
    
    return render(request, "bottles/bottles_sublist.html", context)

def bottles_list_distillery(request, distillery):
    """
    Returns list of all bottles from a distillery
    """
    bottles = Bottle.objects.filter(brand__distillery__name = distillery).order_by('name')
    title = "Distillery: " + distillery
    subtitle = "Brands: "
    brands = Brand.objects.filter(distillery__name = distillery).order_by('name')
    for brand in brands:
        subtitle += brand.name + ", "
    context = {'bottles': bottles, 'title': title, 'subtitle': subtitle[:-2]}
    
    return render(request, "bottles/bottles_sublist.html", context)

def distilleries_list(request):
    """
    Returns list of all distilleries ordered
    """
    distilleries = Distillery.objects.all().order_by('name')
    letters = string.ascii_uppercase
    context = {'distilleries': distilleries, 'letters': letters}
    
    return render(request, "bottles/distilleries.html", context)

def distilleries_list_alpha(request, letter):
    """
    Returns list of all distilleries starting with lettter ordered
    """
    distilleries = Distillery.objects.filter(name__startswith = letter).order_by('name')
    letters = string.ascii_uppercase
    context = {'distilleries': distilleries, 'letters': letters}
    
    return render(request, "bottles/distilleries.html", context)

def brands_list(request):
    """
    Returns list of all brands ordered
    """
    brands = Brand.objects.all().order_by('name')
    letters = string.ascii_uppercase
    context = {'brands': brands, 'letters': letters}
    
    return render(request, "bottles/brands.html", context)

def brands_list_alpha(request, letter):
    """
    Returns list of all brands starting with lettter ordered
    """
    brands = Brand.objects.filter(name__startswith = letter).order_by('name')
    letters = string.ascii_uppercase
    context = {'brands': brands, 'letters': letters}
    
    return render(request, "bottles/brands.html", context)

# Details
def bottle(request, bottle_id):
    """
    Returns specific bottle
    """
    # bottle = Bottle.objects.get(id = bottle_id)
    bottle = get_object_or_404(Bottle, pk = bottle_id)
    context = {'bottle': bottle}
    
    return render(request, "bottles/bottle.html", context)

def distillery(request, distillery_name):
    """
    Returns specific distillery
    """
    distillery = get_object_or_404(Distillery, pk = distillery_name)
    brands = Brand.objects.filter(distillery__name = distillery_name)
    
    context = {'distillery': distillery, 'brands': brands}
    
    return render(request, "bottles/distillery.html", context)

# Distilleries by region.
def region(request, letter):
    # Distilleries of region letter
    distilleries = Distillery.objects.filter(region__iexact = letter).order_by('name')    
    context = {'distilleries': distilleries}
    
    return render(request, 'bottles/region.html', context)

# Add a bottle
@login_required(login_url = '/users/login')
def bottle_new(request):
    if request.method == 'POST':
        form = BottleForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('bottles:bottles_list'))
    else:
        form = BottleForm()
    context = {'form':form}
    
    return render(request, 'bottles/bottle_new.html', context)

# Add a distillery
@login_required(login_url = '/users/login')
def distillery_new(request):
    if request.method == 'POST':
        form = DistilleryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('bottles:distilleries_list'))
    else:
        form = DistilleryForm()
    context = {'form':form}
    
    return render(request, 'bottles/distillery_new.html', context)

# Add a brand
@login_required(login_url = '/users/login')
def brand_new(request):
    if request.method == 'POST':
        form = BrandForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('bottles:brands_list'))
    else:
        form = BrandForm()
    context = {'form':form}
    
    return render(request, 'bottles/brand_new.html', context)

# Edit a bottle
@login_required(login_url = '/users/login')
def bottle_edit(request, bottle_id):
    bottle = get_object_or_404(Bottle, pk = bottle_id)
    if request.method == 'POST':
        form = BottleForm(request.POST, request.FILES, instance = bottle)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('bottles:bottles_list'))
    else:
        form = BottleForm(instance = bottle)
    context = {'form':form}
    
    return render(request, 'bottles/bottle_new.html', context)

# Edit a distillery
@login_required(login_url = '/users/login')
def distillery_edit(request, distillery_name):
    distillery = get_object_or_404(Distillery, pk = distillery_name)
    if request.method == 'POST':
        form = DistilleryForm(request.POST, request.FILES, instance = distillery)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('distillerys:distillerys_list'))
    else:
        form = DistilleryForm(instance = distillery)
    context = {'form':form}
    
    return render(request, 'bottles/distillery_new.html', context)

# Search bottle
def bottle_search(request):
    if 'query' in request.GET:
        bottles =  Bottle.objects.filter(name__icontains = request.GET['query']) 
        letters = string.ascii_uppercase
        context = {'bottles': bottles, 'letters': letters}
    
        return render(request, "bottles/bottles.html", context)
    else:
        message = 'You submitted an empty form.'
        context = {'message': message}
        return render(request, "bottles/error_message.html", context)
        
# Search distillery
def distillery_search(request):
    if 'query' in request.GET:
        distilleries =  Distillery.objects.filter(name__icontains = request.GET['query']) 
        letters = string.ascii_uppercase
        context = {'distilleries': distilleries, 'letters': letters}
    
        return render(request, "bottles/distilleries.html", context)
    else:
        message = 'You submitted an empty form.'
        context = {'message': message}
        return render(request, "bottles/error_message.html", context)
    
# Search brand
def brand_search(request):
    if 'query' in request.GET:
        brands =  Brand.objects.filter(name__icontains = request.GET['query']) 
        letters = string.ascii_uppercase
        context = {'brands': brands, 'letters': letters}
    
        return render(request, "bottles/brands.html", context)
    else:
        message = 'You submitted an empty form.'
        context = {'message': message}
        return render(request, "bottles/error_message.html", context)

# Delete
@login_required(login_url = '/users/login')
def bottle_delete(request, bottle_id):
    """
    Returns specific bottle
    """
    bottle = get_object_or_404(Bottle, pk = bottle_id)
    
    # Only staff can delete bottle
    if request.user.is_staff:       
        bottle.delete()
    else:
        message = "You have no permissions for deleting a bottle"
        context = {'message': message}
        return render(request, "bottles/error_message.html", context)
    
    return redirect(reverse_lazy('bottles:bottles_list'))
@login_required(login_url = '/users/login')

def distillery_delete(request, distillery_name):
    """
    Returns specific distillery
    """
    distillery = get_object_or_404(Distillery, pk = distillery_name)
    
    # Only staff can delete distillery
    if request.user.is_staff:       
        distillery.delete()
    else:
        message = "You have no permissions for deleting a distillery"
        context = {'message': message}
        return render(request, "bottles/error_message.html", context)
    
    return redirect(reverse_lazy('bottles:distilleries_list'))

MaltAuction/bottles/templates/bottles/bottle.html
{% extends "base.html" %}

{% block Contents %}	
	<h2>{{ bottle.name }}</h2>
	<h3>Brand: {{ bottle.brand.name }}</h3>
	<h3>Distillery: {{ bottle.brand.distillery.name }}</h3>
	<img style="width: 100px; float: left; margin-right: 10px" src='{{ MEDIA_URL }}{{ bottle.picture }}' alt=""/><br>		
	{% if bottle.age %}
		<p>{{ bottle.age }} year(s) old</p>
	{% endif %}
	{% if bottle.vintage %}
		<p>Vintage: {{ bottle.vintage }}</p>
	{% endif %}
	{% if bottle.bottled %}
		<p>Bottled: {{ bottle.bottled }}</p>
	{% endif %}
	{% if bottle.distilleryBottling %}
	{% else %}
		<p>Bottled by: {{ bottle.independentBottler }}</p>
	{% endif %}
	<p>{{ bottle.strength }} abv</p>
	{% if bottle.comment %}
		<p>{{ bottle.comment }}</p>
	{% endif %}
	{% if bottle.cask %}
		<p>Cask: {{ bottle.cask }}</p>
	{% endif %}
	{% if bottle.bottles %}
		<p>Bottles: {{ bottle.bottles }}</p>
	{% endif %}
	<div style ="clear: left; float: left; margin-top: 10px">
	<a class="btn btn-small btn-default" href="{% url 'bottles:bottle_delete' bottle.id %}" role="button"><span class="glyphicon glyphicon-remove"></span> Delete</a>
	<a class="btn btn-small btn-default" href="{% url 'bottles:bottle_edit' bottle.id %}" role="button"><span class="glyphicon glyphicon-edit"></span> Edit</a>
	</div>
{% endblock %}

MaltAuction/bottles/templates/bottles/bottle_new.html
{% extends "base.html" %}

{% block Contents %}
	<h2>New bottle</h2>	
	<form id='form' method='post' enctype='multipart/form-data' action=''>{% csrf_token %}
	    {{form.as_p}}
		<p><input type='submit' value='Submit'></p>
	</form>
{% endblock %}

MaltAuction/bottles/templates/bottles/bottles.html
{% extends "base.html" %}

{% block Contents %}
	<div class="btn-toolbar" role="toolbar" aria-label="letters">
		<div class="btn-group" role="group" aria-label="new">
			<a class="btn btn-mini btn-default" href="{% url 'bottles:bottle_new' %}" role="button">New bottle</a>
		</div>
		<div class="btn-group" role="group" aria-label="all">
			<a class="btn btn-mini btn-default" href="{% url 'bottles:bottles_list' %}" role="button">All</a>
		</div>
		<div class="btn-group" role="group" aria-label="letters">
			{% for letter in letters %}
				<a class="btn btn-mini btn-default" href="{% url 'bottles:bottles_list_alpha' letter %}" role="button">{{ letter }}</a>			
			{% endfor %} 
		</div>
	</div>
	{% if bottles %}
		<table class="bottles-list">
	  		<tr>	    		
				{% for bottle in bottles %}
					<td>
						<img style="width:100px;" src='{{ MEDIA_URL }}{{ bottle.picture }}' alt=""/><br>
						<a href="{% url 'bottles:bottle' bottle.id %}" alt="">{{ bottle.name }}</a><br>
						{{ bottle.strength }} %
					</td>
					{% if forloop.counter|divisibleby:"5" %}
						</tr><tr>
					{% endif %}
				{% endfor %}
			</tr>
		</table>
	{% else %}
		<p>No bottles in the database</p>
	{% endif %}
{% endblock %}

{% block Aside %}
<form class="form-inline" role="search" action="{% url 'bottles:bottle_search' %}" method="get">
	<div class="form-group">
		<input type="text" class="form-control" placeholder="Bottle..." name="query">
	</div>
	<button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"> Search</button>
</form>
{% endblock %}

MaltAuction/bottles/templates/bottles/bottles_sublist.html
{% extends "base.html" %}

{% block Contents %}
	{% if bottles %}
		<h2>{{ title }}</h2>
		<h3>{{ subtitle }}</h3>
		<table class="bottles-list">
	  		<tr>	    		
				{% for bottle in bottles %}
					<td>
						<img style="width:75px;" src='{{ MEDIA_URL }}{{ bottle.picture }}' alt=""/><br>
						<a href="{% url 'bottles:bottle' bottle.id %}" alt="">{{ bottle.name }}</a><br>
						{{ bottle.strength }} %
					</td>
					{% if forloop.counter|divisibleby:"5" %}
						</tr><tr>
					{% endif %}
				{% endfor %}
			</tr>
		</table>
	{% else %}
		<p>No bottles in the database</p>
	{% endif %}
{% endblock %}

MaltAuction/bottles/templates/bottles/brand_new.html
{% extends "base.html" %}

{% block Contents %}
	<h2>New brand</h2>	
	<form id='form' method='post' enctype='multipart/form-data' action=''>{% csrf_token %}
	    {{form.as_p}}
		<p><input type='submit' value='Submit'></p>
	</form>
{% endblock %}

MaltAuction/bottles/templates/bottles/brands.html
{% extends "base.html" %}

{% block Contents %}
	<div class="btn-toolbar" role="toolbar" aria-label="letters">
		<div class="btn-group" role="group" aria-label="new">
			<a class="btn btn-mini btn-default" href="{% url 'bottles:brand_new' %}" role="button">New brand</a>
		</div>
		<div class="btn-group" role="group" aria-label="all">
			<a class="btn btn-mini btn-default" href="{% url 'bottles:brands_list' %}" role="button">All</a>
		</div>
		<div class="btn-group" role="group" aria-label="letters">
			{% for letter in letters %}
				<a class="btn btn-mini btn-default" href="{% url 'bottles:brands_list_alpha' letter %}" role="button">{{ letter }}</a>			
			{% endfor %} 
		</div>
	</div>
	{% if brands %}
		<table class="brands-list">
	  		<tr>	    		
	  			<div class="btn-toolbar" role="toolbar" aria-label="letters">
				{% for brand in brands %}
					<div class="btn-group" role="group" aria-label="new">
						<a class="btn btn-small btn-primary" href="{% url 'bottles:bottles_list_brand' brand.name %}" role="button">{{ brand.name }}</a>
					</div>
				{% endfor %}
				</div>
			</tr>
		</table>
	{% else %}
		<p>No brands in the database</p>
	{% endif %}
{% endblock %}

{% block Aside %}
<form class="form-inline" role="search" action="{% url 'bottles:brand_search' %}" method="get">
	<div class="form-group">
		<input type="text" class="form-control" placeholder="Brand..." name="query">
	</div>
	<button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"> Search</button>
</form>
{% endblock %}

MaltAuction/bottles/templates/bottles/distilleries.html
{% extends "base.html" %}

{% block Contents %}
	<div class="btn-toolbar" role="toolbar" aria-label="letters">
		<div class="btn-group" role="group" aria-label="new">
			<a class="btn btn-mini btn-default" href="{% url 'bottles:distillery_new' %}" role="button">New distillery</a>
		</div>
		<div class="btn-group" role="group" aria-label="all">
			<a class="btn btn-mini btn-default" href="{% url 'bottles:distilleries_list' %}" role="button">All</a>
		</div>
		<div class="btn-group" role="group" aria-label="letters">
			{% for letter in letters %}
				<a class="btn btn-mini btn-default" href="{% url 'bottles:distilleries_list_alpha' letter %}" role="button">{{ letter }}</a>			
			{% endfor %} 
		</div>
	</div>
	{% if distilleries %}
		<table class="distilleries-list">
	  		<tr>	    		
				{% for distillery in distilleries %}
					<td>
						<img style="width:150px;" src='{{ MEDIA_URL }}{{ distillery.picture }}' alt=""/><br>
						<a href="{% url 'bottles:distillery' distillery.name %}" alt="">{{ distillery.name }}</a><br>
						<p>{{ distillery.get_region_display }}</p>
						<p>{{ distillery.get_status_display }}</p>
					</td>
					{% if forloop.counter|divisibleby:"5" %}
						</tr><tr>
					{% endif %}
				{% endfor %}
			</tr>
		</table>
	{% else %}
		<p>No distilleries in the database</p>
	{% endif %}
{% endblock %}

{% block Aside %}
<form class="form-inline" role="search" action="{% url 'bottles:distillery_search' %}" method="get">
	<div class="form-group">
		<input type="text" class="form-control" placeholder="Distillery..." name="query">
	</div>
	<button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"> Search</button>
</form>
{% endblock %}

MaltAuction/bottles/templates/bottles/distillery.html
{% extends "base.html" %}

{% block Contents %}
	<h3><a href="{% url 'bottles:bottles_list_distillery' distillery.name %}" alt="">{{ distillery.name }}</a></h3>
	<p>Region: {{ distillery.get_region_display }}</p>
	<p>{{ distillery.get_status_display }}</p>
	<p>Founded: {{ distillery.yearFounded }}</p>				
	{% if distilley.yearClosed %}
		<p>Closed: {{ distillery.yearClosed }}</p>
	{% endif %}
	{% if distilley.webpage %}
		<a href="{{distillery.webpage}}" alt="">Webpage</a>
	{% endif %}
	<p>{{ distillery.description }}</p>
	<img src='{{ MEDIA_URL }}{{ distillery.picture }}' alt=""/>
	<div style ="clear: left; float: left; margin-top: 10px">
	<a class="btn btn-small btn-default" href="{% url 'bottles:distillery_delete' distillery.name %}" role="button"><span class="glyphicon glyphicon-remove"></span> Delete</a>
	<a class="btn btn-small btn-default" href="{% url 'bottles:distillery_edit' distillery.name %}" role="button"><span class="glyphicon glyphicon-edit"></span> Edit</a>
	</div>
{% endblock %}

{% block Aside %}
	{% if brands %}
		<h4>Brands from {{ distillery.name }} distillery</h4>
		{% for brand in brands %}
			<p><a href="#" alt="">{{ brand.name }}</a></p>
		{% endfor %}
	{% else %}
		<h4>No brands from {{ distillery.name }} distillery.</h4>
	{% endif %}
{% endblock %}

MaltAuction/bottles/templates/bottles/distillery_new.html
{% extends "base.html" %}

{% block Contents %}
	<h2>New distillery</h2>	
	<form id='form' method='post' enctype='multipart/form-data' action=''>{% csrf_token %}
	    {{form.as_p}}
		<p><input type='submit' value='Submit'></p>
	</form>
{% endblock %}

MaltAuction/bottles/templates/bottles/error_message.html
{% extends "base.html" %}

{% block Header %}
<h2>Welcome to Malt Auction</h2>
{% endblock %}

{% block Contents %}
	<h2>{{ message }}</h2>	
{% endblock %}

MaltAuction/bottles/templates/bottles/region.html
{% extends "base.html" %}

{% block Contents %}
		<div class='fivecolumns'>
		{% for data in distilleries %}
			{% if forloop.first %}
				<h2>Region: {{ data.get_region_display }}</h2>
			{% endif %}
	    	<div class='cell'>
	    		<div class='celltext'>
	    			<div class='{{data.status}}'>
	    				<a href="{% url 'bottles:distillery' data.name %}">
 							<img src='{{MEDIA_URL}}{{data.picture}}' alt=""/>{{ data.name }} ({{ data.yearFounded }})
 						</a>
	            		<p>{{data.description|truncatewords:"10"}}</p>
					</div>
				</div>
			</div>
			{% if forloop.counter|divisibleby:"5" %}
			</div>
			<div class='fivecolumns'>
			{% endif %}
		{% endfor %}
		</div>
{% endblock %}